---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kluctl --version
    register: kluctl_ver_test_output
  - name: kluctl --version
    debug:
      msg: '{{ kluctl_ver_test_output.stdout }}'
