---
- name: Testing andrewrothstein.kluctl
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kluctl --version'
      ansible.builtin.command: /usr/local/bin/kluctl --version
      changed_when: false
      register: kluctl_ver_test_output
    - name: Output of 'kluctl --version'
      ansible.builtin.debug:
        msg: '{{ kluctl_ver_test_output.stdout }}'
